### ISSUE TITLE
Coding ToDo

### ISSUE THREAD

**Issue by arunesh90** [Lederps/Coding-Lab#1]
- [ ] Do sum tutorials
- [ ] Setup some tests
- [x] Poke Kevin with an stick and scream to him. "LEARN ENCRYPTING SHIT."
- [ ] Learn graphic skillz (stickmans.... Jk)
- [ ] Learn python for websites
- [ ] Perhaps Ruby also?
- [x] Be an duck

<h2>And moar...</h2>.

**Comment by arunesh90** [comment]
MOAR SUGGESTIONS
MOAAAAARRR

**Comment by arunesh90** [comment]
Since you can only assign 1 guy.... i just mention everyone here.
@Lederps/lederps @eXoShini @xKoda
