### ISSUE TITLE
Coding ToDo

### ISSUE THREAD

**Issue by arunesh90** [Lederps/Coding-Lab#2]
@Lederps/lederps 
- [ ] Do sum tutorials
- [ ] Setup some tests
- [x] Poke Kevin with an stick and scream to him. "LEARN ENCRYPTING SHIT."
- [ ] Learn graphic skillz (stickmans.... Jk)
- [ ] Learn python for websites
- [ ] Perhaps Ruby also?
- [x] Be an duck

<h2>And moar...</h2>.

**Comment by arunesh90** [comment]
Re-created because the assign spam i accidently did. 
Spamming mentions
@Lederps/lederps @Lederps/lederps @Lederps/lederps @Lederps/lederps @Lederps/lederps 
![Uwot](/https://images.discordapp.net/eyJ1cmwiOiJodHRwczovL2Rpc2NvcmQuczMuYW1hem9uYXdzLmNvbS9hdHRhY2htZW50cy85ODIyODQ5OTkxMDc3NDc4NC85ODMzOTA5NDI3MDA3NDg4MC8yNS5qcGcifQ.I7e5HNmysjv25RkQg_LUNmIvkaQ.jpg?format=webp)
